Get-WmiObject
Get-CimClass
Get-CimInstance
Get-Service 
Set-Service
Get-ADUser
Set-ADUser
Search-ADAccount
Get-ADGroup
Get-VM
Set-VM
Get-VM | Get-VMNetworkAdapter | Connect-VMNetworkAdapter 
Get-NetConnectionProfile
Set-NetConnectionProfile
Set-NetFirewallProfile
Test-NetConnection
Invoke-WebRequest
Start-Process
Get-EventLog
Get-WinEvent
Get-LocalUser
Invoke-Command
Enter-PSSession
Restart-Computer
Get-ScheduledTask
Get-Printer